- internal/modules/springboot2/springboot2_test.go
- internal/pkg/helpers/prometheus/metrics.go
- internal/pkg/helpers/prometheus/prometheus.go
- internal/pkg/helpers/prometheus/prometheus_test.go
- internal/pkg/logger/logger.go
- internal/pkg/utils/funcs.go
- internal/pkg/utils/funcs_test.go
Fix springboot2 connection leak #13 
Fix StrToMap panic if s is not a ptr
Fix logger panic if logger is nil
> Fix springboot2 connection leak etc.

- modules/charts.go
- modules/job.go
> add runtime charts

- godplugin/plugin.go
- modules/job.go
- modules/registry.go
> remove panicked job from the plugin loop queue

- .gitignore
- .travis.yml
> add travis config

- .circleci/config.yml
- Makefile
- cmd/godplugin/main.go
- go.mod
- godplugin/plugin.go
- modules/all/all.go
- modules/example/charts.go
- modules/example/example.go
- modules/httpcheck/charts.go
- modules/httpcheck/httpcheck.go
- modules/job.go
- modules/module.go
- modules/portcheck/charts.go
- modules/portcheck/portcheck.go
- modules/springboot2/charts.go
- modules/springboot2/springboot2.go
- modules/springboot2/springboot2_test.go
- modules/weblog/categories.go
- modules/weblog/charts.go
- modules/weblog/filter.go
- modules/weblog/get_charts.go
- modules/weblog/patterns.go
- modules/weblog/weblog.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/prometheus_test.go
- pkg/web/client.go
> fix import path

- modules/all/all.go
- modules/httpcheck/charts.go
- modules/httpcheck/httpcheck.go
- modules/httpcheck/httpcheck_test.go
> Httpcheck fix

- modules/charts_test.go
- modules/job.go
- modules/job_test.go
- modules/mock.go
- modules/mock_test.go
- modules/module_base_test.go
- modules/module_test.go
- modules/netdataapi.go
- modules/netdataapi_test.go
- modules/registry.go
- modules/registry_test.go
> [wip] modules test

- cmd/godplugin/main.go
- logger/count_watcher.go
- logger/logger.go
- logger/logger_test.go
> logger test update

- cmd/godplugin/main.go
- go.mod
- go.sum
- godplugin/module_config.go
- godplugin/plugin.go
- modules/httpcheck/httpcheck.go
- modules/job.go
- modules/springboot2/charts.go
- modules/springboot2/springboot2.go
- modules/springboot2/springboot2_test.go
- modules/tcpcheck/worker.go
- pkg/prometheus/metrics.go
- pkg/prometheus/metrics_test.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/prometheus_test.go
- pkg/tail/tail.go
- pkg/tail/tail_test.go
- pkg/utils/funcs_test.go
- pkg/utils/slice.go
- pkg/utils/slice_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- pkg/web/client_test.go
> pkg tests part1

- modules/job.go
> do not use time.Sub for sinceLast calculation

- Dockerfile
- cmd/godplugin/main.go
- conf.d/go.d/example.conf
- docker-compose.yml
- go.mod
- go.sum
- godplugin/module_config.go
- godplugin/plugin.go
- godplugin/plugin_config.go
- pkg/multipath/multipath.go
> add develop docker-compose and fix config path

- godplugin/jobscreate_test.go
- godplugin/jobstart.go
- godplugin/jobstart_test.go
- godplugin/mock.go
- godplugin/mock_test.go
- godplugin/plugin_test.go
- godplugin/setup.go
- godplugin/setup_test.go
- godplugin/tests/go.d.conf-disabled.yml
- godplugin/tests/go.d/module-broken.conf
- godplugin/tests/go.d/module-no-jobs.conf
- godplugin/tests/go.d/module2.conf
- modules/job_test.go
- modules/mock.go
- modules/mock_test.go
- pkg/multipath/multipath_test.go
- pkg/multipath/tests/test.conf
Fix: #28
still a lot of room for improvements
> Plugin test update

- modules/apache/apache.go
- modules/httpcheck/httpcheck.go
- modules/lighttpd/lighttpd.go
- modules/lighttpd2/lighttpd2.go
- modules/nginx/nginx.go
- modules/rabbitmq/rabbitmq.go
- pkg/prometheus/prometheus.go
- pkg/web/client.go
- pkg/web/client_test.go
- pkg/web/request.go
- pkg/web/request_test.go
* move `ProxyName` to web.Request
* move `ProxyPassword` to web.Request
* remove web.HTTPClient (new func now returns *http.Client)
> web client refactor

- modules/weblog/histogram.go
> web_log histogram value fix

- modules/activemq/README.md
- modules/activemq/activemq.go
- modules/activemq/activemq_test.go
- modules/activemq/apiclient.go
- modules/activemq/charts.go
* move unprocessed messages to a separate chart, change algo to `absolute`
* add not simple patterns support for filtering queues, topics
* move api related stuff to a separate file
> activemq bugfix

- godplugin/config.go
- godplugin/config_test.go
- godplugin/jobscreate_test.go
- godplugin/tests/go.d/module-broken.conf
- godplugin/tests/go.d/module-no-jobs.conf
- godplugin/tests/go.d/module1.conf
- godplugin/tests/go.d/module2.conf
```yaml
global:
update_every: 1
other_param: 0
jobs:
- name: job1
- name: job2
```
=>  (same as `go.d.conf`)
```yaml
update_every: 1
other_param: 0
jobs:
- name: job1
- name: job2
> module config: remove global section

- modules/weblog/charts.go
- modules/weblog/weblog.go
- modules/weblog/worker.go
Remove:
* detailed_response_codes (chart them always)
* per_url_charts (chart if categories are set)
> web_log: remove some options

- .travis.yml
- hack/go-build.sh
Reverts netdata/go.d.plugin#126
> Revert "Enable gcc cross-compilation"

- modules/springboot2/README.md
- modules/springboot2/charts.go
- modules/springboot2/springboot2.go
- modules/springboot2/springboot2_test.go
- modules/springboot2/tests/testdata.txt
> refactor springboot2

- godplugin/plugin.go
heartbeat writes newline, so it is a little bit annoying it debug mode
> dont run heartbeat in debug mode

- config/go.d/activemq.conf
- config/go.d/apache.conf
- config/go.d/consul.conf
- config/go.d/httpcheck.conf
- config/go.d/lighttpd.conf
- config/go.d/lighttpd2.conf
- config/go.d/logstash.conf
- config/go.d/nginx.conf
- config/go.d/rabbitmq.conf
- config/go.d/solr.conf
- config/go.d/springboot2.conf
- modules/activemq/activemq.go
- modules/apache/apache.go
- modules/consul/consul.go
- modules/httpcheck/httpcheck.go
- modules/lighttpd/lighttpd.go
- modules/lighttpd2/lighttpd2.go
- modules/logstash/logstash.go
- modules/nginx/nginx.go
- modules/rabbitmq/rabbitmq.go
- modules/solr/solr.go
- modules/springboot2/springboot2.go
- pkg/web/client.go
- pkg/web/client_test.go
- pkg/web/tls.go
shamelessly stolen from telegraf :muscle: :clap: 
it 100% works, tests later
> Web tls config

- conf.d/go.d/oracledb.conf
- modules/nvidia_nvml/README.md
- modules/oracledb/README.md
- remove oracledb.conf
- update oracledb and nvidia_nvml modules readme
> minor fixes

- modules/nvidia_nvml/README.md
- modules/oracledb/README.md
The title on the readmes shows up in netlify under 3 levels, so it needs to be short.
> Change "temporary disabled" to WorkInProgress

- go.mod
- go.sum
https://docs.netdata.cloud/collectors/plugins.d/#writing-plugins-properly
https://github.com/netdata/go-orchestrator/commit/2b790177c79236e1a3a9b25722a6182e49e461bc
> orchestrator update

- cmd/godplugin/main.go
- go.mod
- go.sum
- hack/go-build.sh
> add version

- .circleci/config.yml
- .travis.yml
- Dockerfile.dev
> upgrade go from 1.11 to 1.12

- cmd/godplugin/main.go
- config/go.d/docker_engine.conf
- modules/docker_engine/README.md
- modules/docker_engine/charts.go
- modules/docker_engine/docker_engine.go
- modules/docker_engine/docker_engine_test.go
- modules/docker_engine/testdata/metrics.txt
- modules/x509check/x509check.go
> Docker engine module

- modules/k8s_kubeproxy/charts.go
- modules/k8s_kubeproxy/collect.go
- modules/k8s_kubeproxy/k8s_kubeproxy_test.go
- modules/k8s_kubeproxy/metrics.go
> kubeproxy add http request duration chart

- cmd/godplugin/main.go
- config/go.d/dockerhub.conf
- modules/dockerhub/README.md
- modules/dockerhub/apiclient.go
- modules/dockerhub/charts.go
- modules/dockerhub/collect.go
- modules/dockerhub/dockerhub.go
- modules/dockerhub/dockerhub_test.go
- modules/dockerhub/testdata/repo1.txt
- modules/dockerhub/testdata/repo2.txt
- modules/dockerhub/testdata/repo3.txt
> add dockerhub module

- config/go.d/springboot2.conf
- mocks/conf.d/go.d/springboot2.conf
- modules/springboot2/charts.go
- modules/springboot2/springboot2.go
- pkg/matcher/expr.go
- pkg/matcher/expr_test.go
> support springboot2 URI filter

- modules/logstash/charts.go
> logstash: change memory charts type to "area"

- modules/nginx/README.md
- modules/nginx/apiclient.go
- modules/nginx/charts.go
- modules/nginx/collect.go
- modules/nginx/metrics.go
- modules/nginx/nginx.go
- modules/nginx/nginx_test.go
- modules/nginx/testdata/tengine-status.txt
> nginx: tengine stub status support

- modules/nginx/apiclient.go
- modules/nginx/collect.go
- modules/tengine/apiclient.go
- modules/tengine/collect.go
- modules/tengine/metrics.go
- modules/tengine/tengine.go
- move parsing logic to apiclient
> nginx and tengine cleanups

- pkg/web/request.go
- pkg/web/request_test.go
> add Copy method to web.Request

- config/go.d/httpcheck.conf
- modules/httpcheck/README.md
- modules/httpcheck/charts.go
- modules/httpcheck/collect.go
- modules/httpcheck/httpcheck.go
- modules/httpcheck/httpcheck_test.go
- modules/httpcheck/metrics.go
- pkg/stm/stm.go
- pkg/stm/stm_test.go
- pkg/web/client.go
- pkg/web/duration.go
- add readme
- status calculation fixes
- cleanups
> Httpcheck fixes

- modules/httpcheck/charts.go
- modules/httpcheck/collect.go
- modules/httpcheck/httpcheck_test.go
- modules/httpcheck/metrics.go
reason: https://github.com/netdata/netdata/blob/master/health/health.d/httpcheck.conf
> httpcheck: sycn with py version

- modules/wmi/README.md
- modules/wmi/charts.go
- modules/wmi/collect.go
- modules/wmi/collect_system.go
- modules/wmi/metrics.go
- modules/wmi/wmi.go
- modules/wmi/wmi_test.go
- number of threads
- number of processes
- system uptime
> wmi: add some system metrics

- modules/wmi/collect.go
- modules/wmi/collect_collection.go
- modules/wmi/collect_cpu.go
- modules/wmi/collect_logical_disk.go
- modules/wmi/collect_memory.go
- modules/wmi/collect_net.go
- modules/wmi/collect_os.go
- modules/wmi/collect_system.go
- move collection func to a separate file
- make collect* funcs simple funcs (not methods)
> move collection funcs to a separate file + minor

- config/go.d/httpcheck.conf
- modules/httpcheck/charts.go
- modules/httpcheck/collect.go
- modules/httpcheck/httpcheck.go
- modules/httpcheck/httpcheck_test.go
- modules/httpcheck/metrics.go
- pkg/web/client.go
set:
- dial tcp handshake timeout
- tls handshake timeout
plus httpcheck fixes
Fixes: netdata/netdata#6152
> Web client fix

- modules/dnsmasq_dhcp/charts.go
- modules/dnsmasq_dhcp/dhcp.go
- modules/dnsmasq_dhcp/dhcp_test.go
This is needed for alarms.
related: netdata/netdata#6206
> dnsmasq_dhcp: 2 charts per dhcp-range

- modules/httpcheck/README.md
https://github.com/netdata/go.d.plugin/blob/master/config/go.d/httpcheck.conf#L174
> fix status_accepted due to the latest config file

- config/go.d/dnsmasq_dhcp.conf
> dnsmasq_dhcp: add pihole job

- cmd/godplugin/main.go
- config/go.d/phpdaemon.conf
- modules/phpdaemon/README.md
- modules/phpdaemon/charts.go
- modules/phpdaemon/client.go
- modules/phpdaemon/collect.go
- modules/phpdaemon/metrics.go
- modules/phpdaemon/phpdaemon.go
- modules/phpdaemon/phpdaemon_test.go
- modules/phpdaemon/testdata/fullstatus.json
>  phpdaemon module

- go.mod
- go.sum
> update go-orch version

- hack/go-build.sh
> go-build.sh all: create .tar.gz

- README.md
This pull request adds the vsphere module to the README.md file.
> Add vsphere module to README.md

- modules/vcsa/README.md
- modules/vcsa/charts.go
- modules/vcsa/collect.go
- modules/vcsa/vcsa_test.go
- split one chart into 3
- update readme
> Vcsa minor

- .circleci/config.yml
- .travis.yml
- Dockerfile.dev
- go.mod
- go.sum
> update to go 1.13

- modules/hdfs/charts.go
- modules/hdfs/hdfs_test.go
- modules/hdfs/metrics.go
> hdfs: collect NumFailedVolumes metric

- config/go.d/pihole.conf
> pihone: disable `http://pi.hole` job

- README.md
- config/go.d.conf
> add unbound to the plugin readme and conf

- modules/unbound/unbound_test.go
fix build on a server with unbound installed
> unbound fix build

- modules/logstash/apiclient.go
- modules/logstash/charts.go
- modules/logstash/collect.go
- modules/logstash/logstash.go
- modules/logstash/logstash_test.go
> logstatsh: fix pipelines metrics

- modules/unbound/config/parse.go
> unbound: do not parse already parsed file

- modules/squidlog/collect.go
- modules/squidlog/logline.go
> squidlog: hier code chart dim name fix

- modules/logstash/charts.go
- modules/logstash/client.go
- modules/logstash/collect.go
- modules/logstash/logstash.go
- modules/logstash/logstash_test.go
> logstash: pipeline charts fix

- modules/unbound/client.go
- modules/unbound/client_test.go
> unbound: fix set client network

- modules/mysql/README.md
> Add note about required mysql permissions

- modules/mysql/mysql.go
> mysql: cleanup panic fix

- modules/phpfpm/README.md
- modules/phpfpm/charts.go
- modules/phpfpm/collect.go
related issue https://github.com/netdata/netdata/issues/7868
> phpfpm: per process chart titles fix

- modules/phpfpm/collect.go
- modules/phpfpm/phpfpm.go
- modules/phpfpm/phpfpm_test.go
- modules/phpfpm/testdata/status-full-no-idle.json
fixes bug introduced in https://github.com/netdata/go.d.plugin/pull/327
> phpfpm: fix collect processes info

- modules/cockroachdb/charts.go
- modules/cockroachdb/cockroachdb_test.go
- modules/cockroachdb/metrics.go
> cockroachdb: collect "txn_restarts_possiblereplay"

- cmd/godplugin/main.go
- go.mod
> godplugin: properly identify parse help error

- hack/go-build.sh
- fix shellcheck warnings
- autoformat 
- add `-w` and `-s` flags to ldflags
Per the [Go doc](https://golang.org/cmd/link/#hdr-Command_Line):
```
-s
Omit the symbol table and debug information.
-w
Omit the DWARF symbol table.
```
Before:
```cmd
550 ilyam:go.d.plugin (exclude_build_debug_info *%)$ ls -lfh bin/ | sort
-rw-r--r--   1 ilyam  staff    10M Feb 23 15:27 go.d.plugin-v0.15.0-13-g0688c81-dirty.darwin-386.tar.gz
-rw-r--r--   1 ilyam  staff    10M Feb 23 15:27 go.d.plugin-v0.15.0-13-g0688c81-dirty.darwin-amd64.tar.gz
-rw-r--r--   1 ilyam  staff    10M Feb 23 15:27 go.d.plugin-v0.15.0-13-g0688c81-dirty.freebsd-386.tar.gz
-rw-r--r--   1 ilyam  staff    10M Feb 23 15:27 go.d.plugin-v0.15.0-13-g0688c81-dirty.freebsd-amd64.tar.gz
-rw-r--r--   1 ilyam  staff    10M Feb 23 15:27 …
```
> build: code cleanup and exclude debug info from binary

- .github/workflows/reviewdog.yml
We mistakenly added these to the agent repo instead of this one, add them here instead.
> Added ReviewDog Go linting checks.

- README.md
> add few tips for developing

- modules/dnsquery/dnsquery.go
> dnsquery: fix log spamming

- modules/weblog/logline.go
> weblog: relax logline url verify

- go.mod
- go.sum
- hack/go-build.sh
> build: add freebsd/arm64

- go.mod
- go.sum
> bump go-orch version

- go.mod
- go.sum
> one more bump go-orch version

- modules/weblog/logline.go
- modules/weblog/logline_test.go
> weblog: do not check url syntax

- go.mod
- go.sum
https://github.com/netdata/go-orchestrator/pull/44
> go-orch latest: keepalive function fix

- modules/prometheus/README.md
Nothing major, just doing a little work as I familiarize myself with the Prometheus collector and scope out whether we should do some bigger content on it.
> Add content and clean up Prometheus doc

- modules/mysql/charts.go
- modules/mysql/testdata/MariaDBv10.5.4-[all_slaves_status].txt
- modules/mysql/testdata/MariaDBv10.5.4-galera-[user_statistics].txt
- modules/mysql/testdata/MySQLv8.0.21-[slave_status].txt
Fixes: https://github.com/netdata/netdata/issues/9632#issuecomment-675497420
> mysql: lowercase user/repl connection name

- modules/prometheus/prometheus.go
- modules/prometheus/prometheus_test.go
- pkg/prometheus/matcher/expr.go
- pkg/prometheus/matcher/expr_test.go
- pkg/prometheus/matcher/logical.go
- pkg/prometheus/matcher/logical_test.go
- pkg/prometheus/matcher/matcher.go
- pkg/prometheus/matcher/matcher_test.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/prometheus_test.go
> pkg/prometheus: add filtering

- pkg/tlscfg/README.md
- pkg/tlscfg/config.go
> pkg/tlscfg: add readme

- go.mod
- go.sum
another routing [update](https://github.com/netdata/go-orchestrator/pull/52), i hope we merge them soon 😄
> bump go-orch

- pkg/stm/README.md
> pkg/stm: add README.md

- config/go.d/systemdunits.conf
- go.mod
- go.sum
- modules/systemdunits/client.go
- modules/systemdunits/collect.go
- modules/systemdunits/systemdunits.go
- modules/systemdunits/systemdunits_test.go
- update `github.com/coreos/go-systemd/v22` to the latest master
- add timeout option
> module/systemdunits: add timeout option

- modules/systemdunits/README.md
- modules/systemdunits/charts.go
- modules/systemdunits/client.go
- modules/systemdunits/collect.go
- modules/systemdunits/doc.go
- modules/systemdunits/systemdunits.go
- modules/systemdunits/systemdunits_test.go
> modules/systemdunits: build only on linux

- cmd/godplugin/main.go
> fix netdata TZ env var hack

- agent/module/charts.go
- agent/module/charts_test.go
- config/go.d/example.conf
- modules/example/README.md
- modules/example/charts.go
- modules/example/collect.go
- modules/example/example.go
- modules/example/example_test.go
- modules/example/init.go
This PR adds configurable number of charts, number of dimensions, charts type and allows to create hidden charts.
> modules/example: refactor

- agent/module/charts.go
- agent/module/job.go
Fixes: netdata/netdata#10164
Tested it manually 😅
> agent/module: ignore charts with `type.id` >= 200 (RRD_ID_LENGTH_MAX)

- agent/job/discovery/file/read.go
> agent/discovery/file: log number of jobs in a config file

- config/go.d/unbound.conf
- modules/unbound/README.md
> Unbound: cumulative stats option fix

- modules/unbound/config/parse.go
- modules/unbound/config/parse_test.go
- modules/unbound/config/testdata/valid_include_toplevel.conf
- modules/unbound/config/testdata/valid_include_toplevel2.conf
- modules/unbound/config/testdata/valid_include_toplevel3.conf
> modules/unbound: respect `include-toplevel` directive

- agent/job/build/build.go
> agent/job/build: log job config on building

- modules/filecheck/README.md
> modules/filecheck: add permissions req to the readme

- config/go.d/filecheck.conf
- modules/filecheck/README.md
- modules/filecheck/collect_dirs.go
- modules/filecheck/collect_files.go
- modules/filecheck/filecheck.go
- modules/filecheck/filecheck_test.go
- modules/filecheck/init.go
> Filecheck: make dir size metrics collection optional/configurable

- modules/mysql/collect_version.go
- modules/mysql/mysql_test.go
- modules/mysql/testdata/mariadb/v10.5.4/version.txt
> modules/mysql: simplify version parsing

- modules/dnsdist/dev.md
> modules/dnsdist: add docker setup guide

- modules/weblog/collect.go
- modules/weblog/logline.go
so it is easier debug problems like https://github.com/netdata/netdata/issues/10255
> module/weblog: log first parse error on collect

- modules/weblog/logline.go
Fixes: netdata/netdata#10255
update `isRegMethodValid` func: add all http methods from https://www.iana.org/assignments/http-methods/http-methods.xhtml
> module/web_log: add valid http methods

- docs/how-to-write-a-module.md
- modules/example/charts.go
- modules/example/example_test.go
- modules/example/init.go
https://i.pinimg.com/originals/fe/8f/26/fe8f26548e9c75575a0e0d25a88e58e4.jpg
> docs: add how-to-write-a-module.md

- docs/how-to-write-a-module.md
... just to make it appear a little nicer on Learn.
> Add frontmatter to the dev guide

- modules/vsphere/README.md
Typo in the suggested debug command at the bottom. Should be "./go.d.plugin -d -m vsphere" not "./go.d.plugin -d -m vshpere"
> update `vsphere` module  README.md

- modules/prometheus/group.go
- modules/prometheus/prometheus_test.go
> modules/prometheus: handle spaces in label values

- config/go.d/prometheus.conf
- modules/prometheus/collect.go
- modules/prometheus/prometheus.go
- modules/prometheus/prometheus_test.go
> modules/prometheus: add expected_prefix option

- config/go.d/filecheck.conf
- modules/filecheck/README.md
- modules/filecheck/charts.go
- modules/filecheck/collect.go
- modules/filecheck/collect_dirs.go
- modules/filecheck/collect_files.go
- modules/filecheck/filecheck.go
- modules/filecheck/filecheck_test.go
> modules/filecheck: add patterns support

- README.md
- modules/filecheck/README.md
- modules/squidlog/README.md
- modules/vcsa/README.md
Same source/motivation as netdata/netdata#10651
> Fix broken links

- agent/module/job.go
- logger/severity.go
Related issue https://github.com/netdata/netdata/issues/10753
> agent: log panic stacktrace in the debug mode

- modules/zookeeper/client.go
Fixes: netdata/netdata#10753
I tested the changes locally. No more panic.
> zookeeper: fix panic when using tls connection

- modules/squidlog/squidlog.go
- modules/weblog/parser_test.go
- modules/weblog/weblog.go
- modules/weblog/weblog_test.go
- pkg/logs/csv.go
- pkg/logs/csv_test.go
- pkg/logs/ltsv.go
- pkg/logs/ltsv_test.go
- pkg/logs/parser.go
> pkg/logs: use string for delimiter configuration options

- config/go.d/prometheus.conf
> support openethereum/geth metrics

- pkg/logs/json.go
- pkg/logs/ltsv.go
- pkg/logs/regexp.go
ssia
Reported in https://community.netdata.cloud/t/ltsv-parsing-problem-with-the-go-weblog-plugin/1431
> pkg/logs: remove new line char when reading a line

- modules/vsphere/collect.go
> vsphere: fix scraping metrics when resources are not discovered

- modules/phpfpm/README.md
- modules/phpfpm/init.go
> phpfpm: prefer "socket" if set

- modules/wmi/README.md
- modules/wmi/charts.go
- modules/wmi/collect.go
- modules/wmi/metrics.go
- modules/wmi/wmi_test.go
> wmi: add more OS(OperatingSystem) charts

- README.md
- config/go.d.conf
- config/go.d/haproxy.conf
- modules/haproxy/README.md
- modules/haproxy/charts.go
- modules/haproxy/collect.go
- modules/haproxy/haproxy.go
- modules/haproxy/haproxy_test.go
- modules/haproxy/init.go
- modules/haproxy/testdata/v2.3.10/metrics.txt
- modules/init.go
Initial implementation as discussed in https://github.com/netdata/product/issues/2165
> Initial implementation
Current implementation collects only metrics requested by our SRE team. We need to do some research and extend the collector for sure.
> add haproxy module

- config/go.d/mongodb.conf
- mocks/conf.d/go.d/mongodb.conf
- modules/mongodb/README.md
- modules/mongodb/charts.go
- modules/mongodb/collect.go
- modules/mongodb/connector.go
- modules/mongodb/model.go
- modules/mongodb/mongodb.go
- modules/mongodb/mongodb_test.go
> mongo dbstats charts

- modules/mongodb/README.md
- modules/mongodb/charts.go
- modules/mongodb/collect.go
- modules/mongodb/connector.go
- modules/mongodb/model.go
- modules/mongodb/mongodb.go
- modules/mongodb/mongodb_test.go
Part of #594
Metrics for replica sets including:
- Replication Lag
- Heartbeat latency
- Ping time
> ReplicaSetStatus charts

- modules/mongodb/collect_replsetstatus.go
- modules/mongodb/connector_mock_test.go
- modules/mongodb/model.go
- modules/mongodb/mongodb_test.go
- modules/mongodb/testdata/v5.0.0/dbStats.go
- modules/mongodb/testdata/v5.0.0/replSetStatus.go
- modules/mongodb/testdata/v5.0.0/serverStatus.go
Some more unit tests specially for dbStatus and replica sets and some enchantments  to previous (messages)
> Mongo increase test coverage

- modules/mysql/charts.go
> fix duplicate chart ctx for mysql

- modules/freeradius/charts.go
> fix duplicate chart ctx for freeradius

- modules/k8s_kubelet/charts.go
> fix duplicate chart ctx for kubelet

- modules/coredns/charts.go
> fix duplicate chart ctx for coredns

- modules/vsphere/charts.go
> fix duplicate chart ctx for vsphere

- modules/hdfs/charts.go
Fixes part of #597
Closes #597
> fix duplicate chart ctx for hdfs

- .github/workflows/reviewdog.yml
Equivalent to https://github.com/netdata/netdata/pull/11553, as well as adding a few extra linting types that should be here but were missing.
> Overhaul automated review CI.

- modules/mongodb/README.md
- modules/mongodb/charts.go
- modules/mongodb/collect.go
- modules/mongodb/collect_server_status.go
- modules/mongodb/collect_shard.go
- modules/mongodb/connector.go
- modules/mongodb/connector_mock_test.go
- modules/mongodb/dev.md
- modules/mongodb/model.go
- modules/mongodb/mongodb.go
- modules/mongodb/mongodb_test.go
- modules/mongodb/testdata/v5.0.0/shard.go
Adds mongdb shard metrics.
Part of #594 and resolves netdata/netdata#5897.
> mongodb shard charts and dimensions

- agent/agent.go
The issue reported in https://community.netdata.cloud/t/netdata-container-fails-to-collect-mysql-stats-after-mariadb-restart/1819
On MySQL/MariaDB restart when connecting via Unix socket
> [ DEBUG ] mysql[local] collect_global_status.go:144 executing query: ‘SHOW GLOBAL STATUS’
> [mysql] 2021/10/15 02:30:03 packets.go:122: closing bad idle connection: EOF
> [ INFO ] main[main] agent.go:191 received broken pipe signal (13). Terminating…
I couldn't really replicate SIGPIPE error by killing Netdata process, the main process always terminates children with SIGTERM. 
I assume the following:
- If Netdata exits w/o terminating go.d process the system will close the pipe
- writing to a closed pipe returns an error, so we can update keepAlive function to exit on the error.
---
I tested the …
> agent: dont exit on SIGPIPE

- pkg/socket/client.go
- pkg/socket/client_test.go
- pkg/socket/servers_test.go
- pkg/socket/types.go
> socket client

- modules/mongodb/charts.go
> fix mongodb connections_rate chart context

- modules/mongodb/connector.go
> fetch mongodb replica set stats

- modules/mongodb/collect_replsetstatus.go
- modules/mongodb/collect_shard.go
> fix mongodb handling of replica set charts dimensions 

- modules/snmp/snmp_test.go
@codeguru1 there is a problem: configs in tests are global variables that contain references.
"success when 'dimensions' set" test fails when it is executed after "success when 'max_request_size' set" because we change Config.Options.MaxOIDs.
https://github.com/netdata/go.d.plugin/blob/0a40796d6851829ad7839662dddc1ef21f031f94/modules/snmp/snmp_test.go#L230-L252
---
That is a quick fix. I think it would be better to not use references at all (less error-prone, `a := b` will be enough to make a copy of `b`).
> fix snmp tests

- modules/snmp/collect.go
- modules/snmp/init.go
This commit checks for the return values during oid Get() and removes the gosnmp logger
> SNMP: check for non-existent OIDs during collect()

- config/go.d/snmp.conf
- modules/snmp/config_validator.go
- modules/snmp/init.go
Add more options to auth_proto, priv_proto.
Fix auth/priv flags mismatch
Update snmp.conf accordingly
> SNMP: this commit fixes auth/priv flags mismatch

- modules/wmi/README.md
- modules/wmi/charts.go
- modules/wmi/collect.go
- modules/wmi/collect_thermalzone.go
- modules/wmi/metrics.go
- modules/wmi/testdata/v0.16.0/metrics.txt
- modules/wmi/wmi.go
- modules/wmi/wmi_test.go
> feat(wmi): collect thermalzone metrics

- README.md
> Docsfix: Added SNMP collector to the README

- agent/module/job.go
> fix: do not hardcode context in the runtime charts

- agent/setup.go
> skip reading stock configuration files in k8s

- modules/k8s_kubelet/collect.go
A quick fix (a proper is TODO).
> fix(k8s_kubelet): handle some renamed metrics

- modules/snmp/collect.go
- modules/snmp/snmp_test.go
> snmp: fix integer type

- modules/snmp/charts.go
ssia
Fixes: netdata/netdata#12860
> fix(snmp): set chart units correctly

- modules/snmp/README.md
> docs: add an example of using YAML anchors to simplify multiple-device configuration

- modules/mysql/charts.go
> fix(mysql): mark userstats_cpu chart as not created when adding a new dimensions

- modules/k8s_state/README.md
> fix k8s state readme

- config/go.d.conf
- modules/chrony/chrony.go
There are a few bugs that need to be fixed before enabling it. Will do soon.
> disable chrony by default

- config/go.d/prometheus.conf
> add wireguard job

- modules/vernemq/README.md
- modules/vernemq/charts.go
> vernemq charts fixes requested in netdata#12592

- modules/postgres/README.md
- modules/postgres/charts.go
- modules/postgres/collect.go
- modules/postgres/collect_checkpoints.go
- modules/postgres/collect_databases.go
- modules/postgres/collect_databases_list.go
- modules/postgres/init.go
- modules/postgres/postgres.go
- modules/postgres/postgres_test.go
- modules/postgres/queries.go
- modules/postgres/testdata/v14.4/checkpoints.txt
Part of netdata/netdata#13387
This PR implements collecting [pg_stat_bgwriter](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-BGWRITER-VIEW).
> feat(postgres): collect pg_stat_bgwriter

- agent/module/charts.go
- agent/module/charts_test.go
Solves 2nd point from https://github.com/netdata/netdata/issues/13315#issue-1295784609
> write default dim algorithm/chart type explicitly when unset

- modules/postgres/README.md
- modules/postgres/charts.go
- modules/postgres/collect.go
- modules/postgres/postgres_test.go
- modules/postgres/queries.go
- modules/postgres/testdata/v14.4/txid_wraparound.txt
> feat(postgres): collect txid wraparound and emergency autovacuum

- modules/postgres/README.md
- modules/postgres/charts.go
- modules/postgres/collect.go
- modules/postgres/postgres.go
- modules/postgres/postgres_test.go
- modules/postgres/queries.go
- modules/postgres/testdata/v14.4/wal_archive_files.txt
- modules/postgres/testdata/v14.4/wal_files.txt
> feat(postgres): collect WAL files and WAL Archive files

- modules/postgres/README.md
- modules/postgres/charts.go
- modules/postgres/collect.go
- modules/postgres/postgres_test.go
- modules/postgres/queries.go
- modules/postgres/testdata/v14.4/autovacuum_workers.txt
> feat(postgres): collect autovacuum workers

- modules/postgres/README.md
- modules/postgres/charts.go
- modules/postgres/collect.go
- modules/postgres/postgres.go
- modules/postgres/postgres_test.go
- modules/postgres/queries.go
- modules/postgres/testdata/v14.4/replication_slot_files.txt
- modules/postgres/testdata/v14.4/replication_slot_list.txt
> feat(postgres): collect replication slot files

- README.md
- config/go.d.conf
- config/go.d/wireguard.conf
- go.mod
- go.sum
- modules/init.go
- modules/wireguard/README.md
- modules/wireguard/charts.go
- modules/wireguard/collect.go
- modules/wireguard/wireguard.go
- modules/wireguard/wireguard_test.go
Closes: #461
Fixes netdata/netdata#13462
> feat: add wireguard collector

- agent/agent.go
- agent/module/job.go
Fixes: netdata/netdata#13318
Closes: #757
@vlvkobal we shouldn't obsolete charts when exiting (only on restart), so #757 won't do. My PR is not good (kinda hack via global variable), but I don't have time to fix it properly now and it fixes the problem.
> fix(agent): always call modules cleanup on exit

- modules/mysql/collect.go
- modules/mysql/collect_global_status.go
- modules/mysql/collect_global_vars.go
- modules/mysql/collect_queries_statistics.go
- modules/mysql/collect_slave_status.go
- modules/mysql/collect_user_statistics.go
- modules/mysql/collect_version.go
- modules/mysql/mysql_test.go
> refactor: mysql

- modules/httpcheck/charts.go
> fix(httpcheck): remove spaces in response_status chart dimensions

- modules/postgres/charts.go
- modules/postgres/collect.go
- modules/postgres/do_query_global.go
- modules/postgres/postgres_test.go
- modules/postgres/queries.go
- modules/postgres/testdata/v14.4/xact_query_running_time.txt
> fix(postgres): fix xact and query time

- modules/postgres/README.md
- modules/postgres/charts.go
- modules/postgres/collect.go
- modules/postgres/do_query_columns.go
- modules/postgres/metrics.go
- modules/postgres/postgres.go
- modules/postgres/postgres_test.go
- modules/postgres/queries.go
- modules/postgres/testdata/v14.4/table_columns_stats.txt
> feat(postgres): collect table null columns

- modules/postgres/collect_metrics.go
Tables appear in pg_statio_user_tables before pg_stat_user_tables.
> fix(postgres): fix table vacuum analyze charts creation

- modules/postgres/charts.go
> feat(postgres): human friendly histogram buckets

- agent/job/build/build.go
- agent/job/confgroup/group.go
- agent/module/job.go
> feat: allow to define labels in config

- modules/redis/README.md
- modules/redis/charts.go
> postgres: re-organize charts

- modules/postgres/README.md
Adding a link to the monitoring guide
> Adding a link to the monitoring guide

- modules/redis/README.md
- modules/redis/charts.go
- modules/redis/collect.go
- modules/redis/collect_info.go
- modules/redis/collect_ping_latency.go
- modules/redis/redis_test.go
> feat(redis): collect time elapsed since last RDB save

- modules/redis/README.md
- modules/redis/charts.go
- modules/redis/collect_info.go
- modules/redis/redis.go
> feat(redis): collect master slave link metrics

- agent/module/job.go
Implements netdata/netdata#13788
> feat: disable internal monitoring charts if NETDATA_INTERNALS_MONITORING set to NO

- modules/mysql/README.md
- modules/mysql/charts.go
- modules/mysql/collect.go
- modules/mysql/collect_global_status.go
- modules/mysql/mysql.go
- modules/mysql/mysql_test.go
> feat(mysql): collect Table_open_cache_overflows

- config/go.d/wmi.conf
- pkg/web/request.go
- pkg/web/request_test.go
- pkg/web/web.go
> feat(web): resolve hostname in URL host

- modules/pihole/client/client.go
- modules/pihole/pihole.go
quick Fixes: netdata/netdata#13768
> fix(pihole): respect headers config option

- modules/wmi/README.md
Update documentation adding argument to command
> Add tcp as parameter

- modules/wmi/wmi.go
- pkg/web/request.go
- pkg/web/request_test.go
> fix config unmarshalling with web.HTTP inlined

- README.md
- config/go.d.conf
- config/go.d/ping.conf
- go.mod
- go.sum
- modules/init.go
- modules/ping/README.md
- modules/ping/charts.go
- modules/ping/collect.go
- modules/ping/init.go
- modules/ping/ping.go
- modules/ping/ping_test.go
- modules/ping/prober.go
> feat: add ping collector

- config/go.d/prometheus.conf
- config/go.d/wmi.conf
> fix: don't use prometheus but wmi on localhost

- agent/job/confgroup/group.go
- agent/job/confgroup/group_test.go
- agent/job/confgroup/hostname.go
- config/go.d/wmi.conf
- modules/wmi/wmi.go
- pkg/web/request.go
- pkg/web/request_test.go
requested in netdata/netdata#13921
> replace hostname in job name

- modules/wmi/README.md
Instead of keeping a copy here.
> Point to the instructions of the MSI installer

- modules/prometheus/README.md
Add Prometheus pull from demo site example to README for Prometheus.
> Add prometheus pull from demo site example.

- modules/postgres/queries.go
> fix(postgres): fix permission denied for schema

- modules/prometheus/README.md
- modules/prometheus/cache.go
- modules/prometheus/charts.go
- modules/prometheus/collect.go
- modules/prometheus/init.go
- modules/prometheus/prometheus.go
- modules/prometheus/prometheus_test.go
- add the 'max_time_series' option.
- add the 'application' conf option.
- add "_sum" and "_count" charts for summaries and histograms.
> prometheus updates

- modules/postgres/collect.go
- modules/postgres/do_query_global.go
- modules/postgres/postgres.go
> fix(postgres): do queryXactQueryRunningTime only for v10+

- modules/consul/charts.go
- modules/consul/collect_metrics.go
- modules/consul/consul.go
- modules/consul/consul_test.go
Some metrics are leader/follower only.
> consul agent mode specific charts

- modules/nvme/README.md
- modules/ping/README.md
These metadata are vital for new collectors to appear in the nightly docs
> Adding necessary metadata for new modules

- modules/postgres/do_query_replication.go
> fix(postgres): handle negative WAL delta

- agent/module/charts.go
- agent/module/job.go
- modules/postgres/charts.go
> postgres: add size var to bloat perc charts

- modules/cassandra/README.md
> Add Cassandra readme to learn

- README.md
add a small section to go docs to show how to enable a collector, this can also then be linked to from other docs if/as needed
> add small section on how to enable a go collector

- modules/windows/README.md
This PR is bringing a section in our official documentation to teach users how to pass arguments for windows exporter and how to fix issues related to timeout.
> Add description about options to documentation

- agent/agent.go
- agent/job/vnode/vnode.go
- agent/module/job.go
> disable vhosts api if no vhosts defined

- config/go.d/postgres.conf
> postgres: add jobs with netdata user

- modules/k8s_state/README.md
- modules/k8s_state/charts.go
Change container restarts from rate to count.
https://github.com/netdata/netdata/discussions/14865
> k8sstate: containers restarts/s => restarts

- config/go.d/docker.conf
- modules/docker/README.md
- modules/docker/charts.go
- modules/docker/collect.go
- modules/docker/docker.go
- modules/docker/docker_test.go
Implements part of netdata/netdata#14799
> docker: add per-container stats

- modules/activemq/README.md
- modules/activemq/metadata.yaml
- modules/apache/README.md
- modules/apache/metadata.yaml
- modules/cassandra/README.md
- modules/cassandra/metadata.yaml
- modules/chrony/README.md
- modules/chrony/metadata.yaml
- modules/cockroachdb/README.md
- modules/cockroachdb/metadata.yaml
- modules/whoisquery/README.md
- modules/whoisquery/metadata.yaml
- modules/wireguard/README.md
- modules/wireguard/metadata.yaml
- modules/x509check/README.md
- modules/x509check/metadata.yaml
- modules/zookeeper/README.md
- modules/zookeeper/metadata.yaml
- whoisquery
- wireguard
- x509check
- zookeeper
> update meta and readme

- modules/activemq/README.md
- modules/activemq/metadata.yaml
- modules/apache/README.md
- modules/apache/metadata.yaml
- modules/dnsdist/README.md
- modules/dnsdist/metadata.yaml
- modules/dnsmasq/README.md
- modules/dnsmasq/metadata.yaml
- modules/dnsmasq_dhcp/README.md
- modules/dnsmasq_dhcp/metadata.yaml
@ilyam8 please check dnsmasq_dhcp and if you agree with the scope description let me know to make the readme too.
> Update readmes and fix some yaml inconsistencies

- modules/redis/README.md
- modules/redis/metadata.yaml
- modules/scaleio/README.md
- modules/scaleio/metadata.yaml
- modules/supervisord/README.md
- modules/supervisord/metadata.yaml
- modules/systemdunits/README.md
- modules/systemdunits/metadata.yaml
redis, scaleio, supervisord, systemdunits
> redis update meta and readme

- modules/ntpd/README.md
- modules/ntpd/metadata.yaml
- modules/nvme/README.md
- modules/nvme/metadata.yaml
> ntpd update meta and readme

- modules/pgbouncer/README.md
- modules/pgbouncer/metadata.yaml
- modules/phpdaemon/README.md
- modules/phpdaemon/metadata.yaml
- modules/postgres/README.md
- modules/postgres/metadata.yaml
postgres, phpdaemon, pgbouncer
> add meta and readme

- modules/consul/metadata.yaml
- modules/elasticsearch/metadata.yaml
- modules/redis/metadata.yaml
will mark ready when bugfix is ran for the other ready yamls.
> Yaml updates

- modules/activemq/multi_metadata.yaml
- modules/apache/multi_metadata.yaml
- modules/cassandra/multi_metadata.yaml
- modules/chrony/multi_metadata.yaml
- modules/cockroachdb/multi_metadata.yaml
- modules/consul/multi_metadata.yaml
- modules/coredns/multi_metadata.yaml
- modules/couchbase/multi_metadata.yaml
- modules/couchdb/multi_metadata.yaml
- modules/dnsdist/multi_metadata.yaml
- modules/dnsmasq/multi_metadata.yaml
- modules/dnsmasq_dhcp/multi_metadata.yaml
- modules/dnsquery/multi_metadata.yaml
- modules/docker/multi_metadata.yaml
- modules/docker_engine/multi_metadata.yaml
- modules/dockerhub/multi_metadata.yaml
- modules/elasticsearch/multi_metadata.yaml
- modules/mysql/multi_metadata.yaml
- modules/nginx/multi_metadata.yaml
- modules/postgres/multi_metadata.yaml
- modules/prometheus/multi_metadata.yaml
- modules/redis/multi_metadata.yaml
- modules/vcsa/multi_metadata.yaml
- modules/vernemq/multi_metadata.yaml
- modules/windows/multi_metadata.yaml
- modules/wireguard/multi_metadata.yaml
- modules/x509check/multi_metadata.yaml
- modules/zookeeper/multi_metadata.yaml
Schema update in netdata/netdata#15470
> meta update multi instance key

- modules/k8s_state/README.md
- modules/k8s_state/charts.go
same changes we did for cgroups plugin in netdata/netdata#15216
> remove unneeded k8s state labels

- modules/mysql/multi_metadata.yaml
> Updating icons to svg

- modules/consul/multi_metadata.yaml
- modules/hdfs/multi_metadata.yaml
- modules/nvme/multi_metadata.yaml
- modules/openvpn/multi_metadata.yaml
- modules/openvpn_status_log/multi_metadata.yaml
- modules/prometheus/multi_metadata.yaml
- modules/prometheus/wip_meta.yaml
- modules/scaleio/multi_metadata.yaml
- modules/systemdunits/multi_metadata.yaml
- modules/windows/multi_metadata.yaml
- modules/wireguard/multi_metadata.yaml
- modules/zookeeper/multi_metadata.yaml
Also removed dup entry:
> name: NUT
>        link: https://github.com/HON95/prometheus-nut-exporter
> review images for integrations from security to windows systems

- modules/prometheus/metadata.yaml
- modules/weblog/metadata.yaml
> Fixing icons in Go plugin

- modules/prometheus/metadata.yaml
- modules/weblog/metadata.yaml
> Fix categories icons

- modules/ping/metadata.yaml
- modules/prometheus/metadata.yaml
- modules/whoisquery/metadata.yaml
> Update prometheus metadata.yaml

- modules/nvidia_smi/charts.go
- modules/nvidia_smi/collect_xml.go
- modules/nvidia_smi/nvidia_smi_test.go
- modules/nvidia_smi/testdata/rtx-4090-driver-535.xml
Fixes issue netdata/netdata#15755
> fix(nvidia_smi): handle renaming power_readings to gpu_power_readings

- modules/activemq/metadata.yaml
- modules/apache/metadata.yaml
- modules/elasticsearch/metadata.yaml
- modules/envoy/metadata.yaml
- modules/geth/metadata.yaml
- modules/k8s_kubelet/metadata.yaml
- modules/k8s_kubeproxy/metadata.yaml
- modules/lighttpd/metadata.yaml
- modules/mysql/metadata.yaml
- modules/nginx/metadata.yaml
- modules/nginxvts/metadata.yaml
- modules/postgres/metadata.yaml
- modules/pulsar/metadata.yaml
- modules/redis/metadata.yaml
- modules/springboot2/metadata.yaml
- modules/zookeeper/metadata.yaml
Reverts netdata/go.d.plugin#1318
> Revert "Update related resources sections to use ids."

- config/go.d/prometheus.conf
Added CrowdSec metrics URL to prometheus.conf.
> added CrowdSec Prometheus metrics URL

- README.md
- config/go.d.conf
- config/go.d/upsd.conf
- modules/init.go
- modules/upsd/README.md
- modules/upsd/charts.go
- modules/upsd/client.go
- modules/upsd/collect.go
- modules/upsd/metadata.yaml
- modules/upsd/upsd.go
- modules/upsd/upsd_test.go
- modules/upsd/variables.go
Fixes part of netdata/netdata#15115
> add upsd (nut) collector

- config/go.d/web_log.conf
- modules/weblog/README.md
- modules/weblog/charts.go
- modules/weblog/collect.go
- modules/weblog/init.go
- modules/weblog/logline.go
- modules/weblog/metadata.yaml
- modules/weblog/metrics.go
- modules/weblog/weblog.go
- modules/weblog/weblog_test.go
Fixes: netdata/netdata#16017
initial implementation, only min/avg/max values.
> add simple custom numeric field

- modules/prometheus/metadata.yaml
related to https://github.com/netdata/netdata/pull/16126
> Remove second category from three prometheus integrations

- modules/prometheus/metadata.yaml
Update categorization of dynatrace
> Update categorization of dynatrace

- Makefile
- hack/go-build.sh
> add version to config.tar.gz

- go.mod
- go.sum
- pkg/logs/lastline.go
> add ReadLastLines func

- modules/traefik/metadata.yaml
> chore(traefik): fix typo in metadata.yaml

- modules/mysql/metadata.yaml
related to https://github.com/netdata/website/pull/382.
> Use proper icon for percona sql

- modules/isc_dhcpd/metadata.yaml
Closes https://github.com/netdata/learn/issues/1877
> Fix isc_dhcpd conf file name

- agent/executable/name.go
- go.mod
- go.sum
- slogger/default.go
- slogger/level.go
- slogger/slogger.go
- slogger/slogger_test.go
> add structured logger

- modules/httpcheck/charts.go
- modules/httpcheck/collect.go
- modules/httpcheck/httpcheck_test.go
- modules/httpcheck/metadata.yaml
- modules/httpcheck/metrics.go
> httpcheck: treat redirect as success if 301 in accepted

- modules/prometheus/metadata.yaml
SEO Changes for Collector names
> SEO Changes for Collector names

- modules/nvme/exec.go
- modules/nvme/init.go
Use [ndsudo](https://github.com/netdata/netdata/pull/16614) instead of `sudo` + `nvme`.
> nvme: use ndsudo if available

- modules/weblog/logline.go
- modules/weblog/logline_test.go
> weblog: HTTP/3 support

- modules/httpcheck/charts.go
- modules/httpcheck/collect.go
- modules/httpcheck/httpcheck.go
- modules/httpcheck/httpcheck_test.go
- modules/httpcheck/init.go
- modules/httpcheck/metadata.yaml
- modules/httpcheck/metrics.go
> httpcheck: add header_match

- modules/prometheus/metadata.yaml
- pkg/prometheus/client.go
- pkg/prometheus/client_test.go
> prometheus: read from file

- modules/weblog/init.go
> weblog: read last N lines on start: 1=>100

- modules/systemdunits/metadata.yaml
Follow up on https://github.com/netdata/netdata/pull/16845
> Include timer units failed state alert as default

- modules/activemq/integrations/activemq.md
- modules/activemq/metadata.yaml
- modules/consul/integrations/consul.md
- modules/consul/metadata.yaml
- modules/vsphere/integrations/vmware_vcenter_server.md
- modules/vsphere/metadata.yaml
- pkg/prometheus/selector/README.md
sed doesn't seem to have picked these up in my local run, did it with vscode search and replace
we need to do the same in netdata/netdata
> fix links that were missed

- modules/.directory
- modules/cockroachdb/metadata.yaml
- modules/consul/metadata.yaml
- modules/dnsmasq_dhcp/metadata.yaml
- modules/dnsquery/metadata.yaml
- modules/docker/metadata.yaml
- modules/elasticsearch/metadata.yaml
- modules/hdfs/metadata.yaml
- modules/k8s_kubelet/metadata.yaml
- modules/mysql/metadata.yaml
- modules/nvme/metadata.yaml
- modules/pihole/metadata.yaml
- modules/ping/metadata.yaml
- modules/portcheck/metadata.yaml
- modules/postgres/metadata.yaml
- modules/redis/metadata.yaml
- modules/systemdunits/metadata.yaml
- modules/upsd/metadata.yaml
- modules/vcsa/metadata.yaml
- modules/vernemq/metadata.yaml
- modules/vsphere/metadata.yaml
- modules/weblog/metadata.yaml
- modules/whoisquery/metadata.yaml
- modules/windows/metadata.yaml
- modules/x509check/metadata.yaml
@ilyam8 after this we need a release, so we don't have broken links in the app
related to https://github.com/netdata/netdata/pull/16954 that should've changed these in the first place.
> Fix health links
