godplugin/plugin_test.go, modules/apache/apache.go, modules/apache/apache_test.go, modules/example/example.go, modules/example/example_test.go, modules/httpcheck/httpcheck.go, modules/httpcheck/httpcheck_test.go, modules/job.go, modules/job_test.go, modules/mock.go, modules/mock_test.go, modules/module.go, modules/nginx/nginx.go, modules/nginx/nginx_test.go, modules/portcheck/portcheck.go, modules/portcheck/portcheck_test.go, modules/rabbitmq/rabbitmq.go, modules/rabbitmq/rabbitmq_test.go, modules/springboot2/springboot2.go, modules/springboot2/springboot2_test.go
`GatherMetrics` => `Collect`
I was thinking of renaming `modules` to `collectors`, but no, they should stay as modules for the consistent across all plugins.
=> GatherMetrics rename

godplugin/loopqueue.go, godplugin/plugin.go
> if you kill netdata with -9, netdata will immediately exit without killing its plugins. So, the only way for a plugin to exit is to detect that writing to its stdout gives errors.
=> plugin hearbeat

modules/springboot2/springboot2.go, modules/springboot2/springboot2_test.go, modules/springboot2/tests/testdata2.txt, pkg/prometheus/metrics.go, pkg/prometheus/metrics_test.go
some springboot2 use `jvm_threads_daemon` while others use `jvm_threads_daemon_threads`
=> fix springboot2 metrics name

modules/pihole/client/client_test.go, modules/pihole/client/types.go, modules/pihole/collect.go, modules/pihole/pihole_test.go
This PR fixes gravity.list update time calculation when the file is not exists.
Before the PR:
- wrong time reported
After the PR:
- value is not reported
if gravity list exists:
```json
{
"file_exists": true,
"absolute": 1561159378,
"relative": {
"days": "2",
"hours": "07",
"minutes": "40"
}
}
```
if not (deleted, moved)
```json
{
"file_exists": false
}
```
=> pihole: gravity list last update fix

modules/scaleio/README.md, modules/scaleio/queries.go
It is not in use and breaks ScaleIO/VxFlex v3 monitoring
Fixes: netdata/netdata#6475
=> scaleio: Remove numOfScsiInitiators

.travis/netdata_sync.sh
As of https://github.com/netdata/netdata/pull/6557 we will be keeping go.d version within packaging/go.d.version,.
This PR changes where we make the modification, simple as that
[ci skip]
=> netdata/packaging: Adjust go.d version update process

modules/httpcheck/README.md, modules/httpcheck/charts.go, modules/httpcheck/collect.go, modules/httpcheck/httpcheck.go, modules/httpcheck/httpcheck_test.go, modules/httpcheck/metrics.go
This adds the current state duration chart (from portcheck) to httpcheck as well. We needed this because we wanted to be able to alert on flapping HTTP checks (IE the HTTP checks are allowed to fail every so often but if they fail repeatedly in a time frame then there might be an underlying issue).
=> Add Current State Duration to HTTPcheck

modules/hdfs/README.md, modules/zookeeper/README.md
Hey @ilyam8, I noticed that the READMEs for the new HDFS and Zookeeper modules, once they get generated by our docs site, don't render correctly. The unordered list gets turned into a big, messy paragraph.
Here's a picture of how the HDFS page looks right now:
I cleaned up the syntax and tested it out on a local build of the docs site and things work as expected after these changes.
Not sure _why_ GitHub and mkdocs render Markdown quite so differently, but that's for another time...
=> Fix markdown syntax HDFS/Zookeeper module pages

modules/coredns/README.md, modules/docker_engine/README.md
As I've been working on the Learn site I began pulling all the `.md` files from this repo to build the site, much like what the current docs site does, but the Learn site's Markdown parser failed on these two files.
So, I've cleaned them up and even aligned them with the core repo's Markdown linter :stuck_out_tongue:
=> Markdown syntax fixes

config/go.d/coredns.conf, config/go.d/k8s_kubelet.conf, modules/k8s_kubelet/collect.go, modules/k8s_kubelet/kubelet.go, modules/k8s_kubelet/kubelet_test.go, modules/k8s_kubelet/testdata/token.txt, modules/rabbitmq/client.go, modules/rabbitmq/rabbitmq_test.go
Fixes: netdata/netdata#7188
This PR:
- coredns: new job `http://kube-dns.kube-system.svc.cluster.local:9153/metrics`
- kubelet: new job  `https://localhost:10250/metrics`
- kubelet: reads `/var/run/secrets/kubernetes.io/serviceaccount/token` and uses bearer token authorization doing api calls.
- rabbitmq: fix `/api/nodes` call
=> coredns, kubelet fixes

modules/freeradius/freeradius.go, modules/freeradius/freeradius_test.go
- Replace incorrect function calls for decoding 'access-rejects' and 'proxy-access-rejects'  #337 .
=> freeradius reject metrics decoding fix

modules/whoisquery/README.md
One-line fix to align the new whois collector with the rest of the links throughout the repo. This one is broken on the Learn site.
=> Fix broken link to documentation

go.mod, go.sum
really need to consider moving orchestrator back to this repo 🤣 
bugfix: https://github.com/netdata/go-orchestrator/pull/43
=> bump go-orch: fix adjust min update every

modules/pulsar/README.md, modules/pulsar/pulsar.go
TODO: it is impossible to chart if there are a lot of subscriptions/topics (chart are kind of broken). I guess we need to remove it this option and show only summary chart.
=> pulsar: disable topic chart by default

modules/openvpn/client/client.go, modules/openvpn/client/client_test.go, modules/openvpn/collect.go, modules/openvpn/openvpn.go, modules/openvpn/openvpn_test.go
=> openvpn: use `Common Name` as username if `Username` is `UNDEF`

cmd/godplugin/main.go
Respect NETDATA_USER_CONFIG_DIR when NETDATA_STOCK_CONFIG_DIR not set and vice versa.
Fixes: netdata/netdata#9481
=> NETDATA_*_CONFIG_DIR env vars fix

README.md, config/go.d.conf, modules/apache/apache.go, modules/bind/bind.go, modules/freeradius/freeradius.go, modules/lighttpd/lighttpd.go, modules/mysql/mysql.go, modules/nginx/nginx.go, modules/phpfpm/phpfpm.go, modules/rabbitmq/rabbitmq.go, modules/squidlog/squidlog.go, modules/weblog/weblog.go
File lock job registry was added
- python.d: https://github.com/netdata/netdata/pull/9564
- go.d: https://github.com/netdata/go-orchestrator/pull/45
- netdata daemon lock dir: https://github.com/netdata/netdata/pull/9584
It should be relatively safe to enable all rewritten in go python modules.
=> Enable disabled modules

config/go.d/prometheus.conf
These are jobs from the https://github.com/prometheus/prometheus/wiki/Default-port-allocations
Some exporters like (netdata, telegraf were excluded).
=> module/prometheus: add more jobs

hack/go-build.sh
> Go 1.15 drops support for 32-bit binaries on macOS, iOS, iPadOS, watchOS, and tvOS (the darwin/386 and darwin/arm ports)
https://golang.org/doc/go1.15#darwin
=> build: remove darwin/386

config/go.d/web_log.conf, go.mod, go.sum, modules/weblog/README.md, modules/weblog/parser.go, modules/weblog/parser_test.go, modules/weblog/weblog.go, pkg/logs/json.go, pkg/logs/json_test.go, pkg/logs/parser.go, pkg/logs/regexp_test.go
This is a JSON log parser. It reads JSON files and maps fields according to the `json_config->mapping` configuration. The parser expects each line to contain single JSON entry.
If this PR is accepted, I'll push small weblog PR that makes use of JSON parser.
JSON logs are more verbose than CSV-ish files, but JSON has some clear advantages:
- it's much easier to parse and query JSON files from command line(for example using `jq`) for quick troubleshooting,
- it's easier to import them into other tools/services for further processing,
- data types might be preserved.
Some tools provide option to generate JSON logs, e.g. nginx.
`json.Unmarshall()` is being used to decode JSON files. All values read by `json.Unmarshall()` are converted back to strings before they're passed to `LogLine`.
- …
=> Added JSON log parser

agent/agent.go
Netdata daemon doesnt restart plugin if its exit code is not 0 (even if it has been sending data for a while).
I did some tests on k8s and somehow/sometimes `go.d.plugin` got SIGPIPE on some nodes after fresh install, netdata was running tho. I think we need to exit 0 and allow netdata to restart the plugin.
=> agent: exit 0 on SIGPIPE

agent/job/build/build.go, agent/job/discovery/file/read.go
seems better place to log number of jobs then in https://github.com/netdata/go.d.plugin/pull/474
=> agent/job/build: log number of jobs in a config group

modules/elasticsearch/README.md, modules/example/README.md, modules/filecheck/README.md, modules/isc_dhcpd/README.md, modules/mysql/README.md, modules/prometheus/README.md, modules/systemdunits/README.md
from #493
- before
```cmd
0 go.d.plugin (master)$ grep "step-by-step/step-04" -R *
modules/isc_dhcpd/README.md:directory](/docs/step-by-step/step-04.md#find-your-netdataconf-file), which is typically at `/etc/netdata`.
modules/systemdunits/README.md:directory](/docs/step-by-step/step-04.md#find-your-netdataconf-file), which is typically at `/etc/netdata`.
modules/example/README.md:directory](/docs/step-by-step/step-04.md#find-your-netdataconf-file), which is typically at `/etc/netdata`.
modules/filecheck/README.md:directory](/docs/step-by-step/step-04.md#find-your-netdataconf-file), which is typically at `/etc/netdata`.
modules/mysql/README.md:directory](/docs/step-by-step/step-04.md#find-your-netdataconf-file), which is typically at `/etc/netdata`. …
```
=> Change configure doc to reflect new standard leftovers

modules/systemdunits/charts.go, modules/systemdunits/client.go, modules/systemdunits/collect.go, modules/systemdunits/init.go, modules/systemdunits/systemdunits.go, modules/systemdunits/systemdunits_test.go
Fixes: #499
Fix is to use `ListUnits` if systemd version < 230 and filter units on our side, if systemd version 230+ nothing changed - we keep using `ListUnitsByPatterns`.
---
@thiagoftsm could you test it on old Centos?
```cmd
git clone https://github.com/ilyam8/go.d.plugin --branch=systemdunits_listunits_comp_fix godsystemd
cd godsystemd
hack/go-build.sh
bin/godplugin -d -m systemdunits
```
=> systemdunits: use appropriate ListUnits function depends on systemd version

cmd/godplugin/main.go
This helps in debugging problems when users show their debug log
```cmd
0 go.d.plugin (log_version_and_user *)$ bin/godplugin -d -m example
[ DEBUG ] main[main] main.go:111 plugin: name=go.d, version=v0.25.0-20-gffe61a9-dirty
[ DEBUG ] main[main] main.go:113 current user: name=ilyam, uid=501
...
```
=> log plugin version and current user name/uid on start

README.md, config/go.d/dnsmasq.conf, modules/dnsmasq/README.md, modules/dnsmasq/charts.go, modules/dnsmasq/collect.go, modules/dnsmasq/dev.md, modules/dnsmasq/dnsmasq.go, modules/dnsmasq/dnsmasq_test.go, modules/dnsmasq/init.go, modules/init.go
https://manpages.debian.org/stretch/dnsmasq-base/dnsmasq.8.en.html#NOTES
> The cache statistics are also available in the DNS as answers to queries of class CHAOS and type TXT in domain bind. The domain names are cachesize.bind, insertions.bind, evictions.bind, misses.bind, hits.bind, auth.bind and servers.bind. An example command to query this, using the dig utility would be
=> add dnsmasq dns forwarder collector

modules/dnsdist/metrics.go
After to have problems with datatype, we decided to convert everything to float64 to avoid problems.
=> dnsdist: change metrics data type to float64

modules/vernemq/charts.go
[Is counter type](https://github.com/vernemq/vernemq/blob/95ad92497ac61b221a0db217793872daa6a6fb20/apps/vmq_server/src/vmq_metrics.erl#L1016-L1017).
=> vernemq: fix `netsplit` chart dims algorithm

agent/agent.go, agent/job/state/state.go, agent/job/state/state_test.go
Fixes: #520
This PR changes job state store structure.
**The goal is to recognize the job**. This implemented by adding a config hash to the job states store key.
Current: `map[moduleName][jobName]state`
```cmd
[ilyam@pc netdata]$ sudo cat god-jobs-statuses.json | head -n 20
{
"activemq": {
"local": "failed"
},
"apache": {
"local": "failed"
},
"bind": {
"local": "failed"
},
"cockroachdb": {
"local": "failed"
},
"consul": {
"local": "failed"
},
"coredns": {
"coredns": "failed"
},
"dnsdist": {
```
After this PR: `map[moduleName][jobName:cfgHash]state`
```cmd
[ilyam@pc netdata]$ sudo cat god-jobs-statuses.json | head -n 20
{
"activemq": {
"local:14596621561266494414": "failed"
},
"apache": {
"local:1189662825161939815": "failed",
"local:17111437997877908439": "failed"
},
"bind": { …
```
=> agent/job/state: proprely handle jobs with same module/name

agent/job/build/build.go, agent/job/build/cache.go
Fixes: #522
Common flow is: `job.Check() ? job.Start() : drop`
We do `Check` only once, however there are some cases when we want to retry it and dont give up after first fail attempt. 
**1.** There is `autodetection_retry` configuration option.
```yaml
```
If its value > 0 we try to `Check()` every `autodetection_retry` and **never** give up.
**2**. Sometimes we need to retry finite number of times and do it w/o any configuration, current cases:
- the job was active before the restart
- the job is k8s job and there is a chance that a service is not ready to serve requests for some time after a container creation.
---
**1** was working, but **2** wasn't. This PR fixes it.
**Consider this PR as a quick workaround**, writing it i understood that there is logical/design problems and we need …
=> agent: fix job detection retry

config/go.d/prometheus.conf
Hello Netdata folks.
First of all thank you for your work on this awesome tool 💛 
I tried to monitor a [Traefik](https://github.com/traefik/traefik) (v2) reverse proxy using Netdata. However it seems the documentation [here](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/traefik) doesn't apply anymore for version 2.
So I decided to use the prometheus metrics endpoint that can be [configured](https://doc.traefik.io/traefik/observability/metrics/prometheus/) on the Traefik side and the prometheus collector on Netdata side.
I did not find the metrics url in the base *prometheus.conf*, and I thought that could be nice to add it. So we keep the "0 configuration required" mindset that we can find in a lot of Netdata features. What do you think ? 
The only downside that I can …
=> add traefik metrics endpoint to prometheus.conf

modules/dnsmasq/README.md, modules/dnsmasq/charts.go, modules/dnsmasq/collect.go, modules/dnsmasq/dnsmasq_test.go
Fixes: #547
`cache_entries = insertions - evictions` was a wrong assumption, see https://github.com/netdata/go.d.plugin/issues/547#issuecomment-769818811
This PR removes `cache_entries` metric, because it is misleading. It looks like it is impossible to get current number of entries in the cache from the provided cache statistics.
=> modules/dnsmasq: remove `cache_entries` metric

config/go.d/prometheus.conf, modules/prometheus/README.md, modules/prometheus/collect_gauge_counter.go, modules/prometheus/init.go, modules/prometheus/prometheus.go, modules/prometheus/prometheus_test.go
Fixes: #531
This PR allows to change dimension algorithm from `incremental` to `absolute` for cumulative metrics. Added new configuration option `force_absolute_algorithm`.
Pattern syntax is https://golang.org/pkg/path/filepath/#Match, example:
```yaml
jobs:
- name: ...
url: ...
force_absolute_algorithm:
- '*_sum'
- '*_count'
```
=> modules/prometheus: add `force_absolute_algorithm` config option

agent/job/build/build.go, agent/job/job.go, agent/module/job.go
Fixes: #549
This PR fixes agent memory leak. For every configuration job we create a logger instance and register it 
https://github.com/netdata/go.d.plugin/blob/196e3eb42a40e9e86705165fbfeadd8f0741c264/logger/logger.go#L54-L60
> GlobalMsgCountWatcher.Register(logger)
That is current log flood protection implementation - there is global registry that contains logger instances references, it iterates over them every second and resets logged messages counter.
But we never unregister them for unsuccessful jobs (Check() returns false).
---
Test plan:
- set `autodetection_retry: 10` in the default `prometheus.conf`
- observe `go.d.plugin` memory consumption on the netdata dashboard (Applications->mem->apps.mem)
The difference before and after the patch is clearly visible:
=> agent: fix mem leak

README.md, config/go.d.conf, config/go.d/supervisord.conf, go.mod, go.sum, modules/init.go, modules/supervisord/README.md, modules/supervisord/charts.go, modules/supervisord/client.go, modules/supervisord/collect.go, modules/supervisord/dev.md, modules/supervisord/init.go, modules/supervisord/supervisord.go, modules/supervisord/supervisord_test.go
Fixes: netdata/netdata#4852
This PR adds initial [Supervisor](http://supervisord.org/) monitoring.
Collected metrics:
- Summary
- Running/non-running processes
- [Per Process' group](http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getProcessInfo)
- Running/non-running processes
- State code (per process)
- Exit status (per process)
- Uptime (per process)
- Downtime (per process)
@ekexcello i decided to add [all the summary charts](https://github.com/netdata/netdata/issues/4852#issuecomment-758039791) in the 2nd PR, i think we need to discuss them a little bit more.
=> add supervisord module

.devcontainer/devcontainer.json
Summary
With the existence of the .devcontainer directory, when a user opens the repository using VS Code, they will be automatically prompted to re-open the directory from inside the developer container. T
The VS Code window is connected to that container, being able to both use extensions to facilitate programming, tools. to check that the code is according to our standards (e.g flake8) and use VS Code sidebar as a GUI for file navigation inside the container. Finally, VS Code syncs the directory that we just opened inside the container, meaning that any file we place from our host machine into that directory (e.g netdata), it will be synced inside the container.
The developer container contains all the required dependencies to build from source:
- netdata
- python.d.plugin
- …
=> Support VS Code container deven

config/go.d/pihole.conf, modules/pihole/pihole.go
Fixes: netdata/netdata#10763
Related https://github.com/netdata/netdata/issues/9642
Gathering data every second is a problem for Raspberry Pi devices, see the above issues.
=> pihole: set default update_every and http timeout to 5

.gitignore, CODE_OF_CONDUCT.md, README.md
This is part of an effort to align all the netdata repos into the same structure and quality, with aim to foster use contribution.
We will remove all community files (e.g contributing) from all our repos and instead use a set of default community health files that are located in [netdata/.github](https://github.com/netdata/.github). GitHub automatically detects those files and links them in all the repos at the appropriate places (e.g in PR tab, above the opens PRs it has a tool tip advising user to check the contributing guidelines).
You can read more about the health files in the README of the .github repository.
All the community files have been revamped.
=> Revamp readme

README.md
Once this README is ingested and published on Learn, this one relative link to the development guide gets mangled and ends up broken. This PR aligns it with other absolute links, such as to all the modules above.
I will eventually try to figure out how to make all these links work properly, but I need more time and this quick PR will fix the one broken link until then.
=> Fix broken link to dev guide

modules/weblog/logline.go
It is proper in the module `README`, but wrong in source code comments.
=> web_log: Fix small typo

modules/vernemq/collect.go, modules/vernemq/vernemq_test.go
I noticed `queue_messages_current` metric is negative on our Netdata Agents (Cloud).
---
These are `queue_message_*` metrics:
- `queue_message_in`: the number of PUBLISH packets received by MQTT queue processes.
- `queue_message_out`: the number of PUBLISH packets sent from MQTT queue processes.
- `queue_message_drop`: the number of messages dropped due to full queues.
- `queue_message_expired`: the number of messages which expired before delivery.
- `queue_message_unhandled`: the number of unhandled messages when connecting with clean session=true.
We shouldn't take into account drop and unhandled calculating messages currently in the queues.
=> modules/vernemq: fix calculation of messages currently in the queues

go.mod, go.sum, modules/whoisquery/provider.go
Fixes: #574
The fix is using https://github.com/araddon/dateparse for parsing the expiration date. The library allows parsing date strings without knowing the format in advance.
=> whoisquery: fix expiration date parsing

modules/mysql/collect.go, modules/mysql/mysql.go
Fixes: netdata/netdata#11131
| Function    | Description |
| ----------- | ----------- |
| Init      | called only once, **if fails we never retry the job**       |
| Check     | called every `autodetection_retry` seconds if configured, otherwise only once |
| Collect   | called every `update_every` seconds        |
We create a connection to the DB in the Init(). That is the reason why `autodetection_retry` doesn't work for the `mysql` collector.
This PR moves a connection creating to the Collect().
=> mysql: move opening a db connection to the Collect

modules/vernemq/README.md, modules/vernemq/charts.go, modules/vernemq/collect.go, modules/vernemq/vernemq_test.go
It is not possible to calculate messages currently in the queue using "queue_message_*" metrics.
=> vernemq: remove "queue_messages_in_queues" chart

modules/mysql/charts.go
Fixes: netdata/netdata#11485
- [Innodb_buffer_pool_read_ahead](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_read_ahead) is in `pages`
- [Innodb_buffer_pool_read_ahead_evicted](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_read_ahead_evicted) is in `pages`
- [Innodb_buffer_pool_read_ahead_rnd](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_read_ahead_rnd) is in (read-ahead) `operations`
Can't be in the same chart, this PR splits "innodb_buffer_pool_read_ahead" into 2 charts.
=> split Mysql innodb_buffer_pool_read_ahead into 2 charts

config/go.d/nginx.conf
Because that is [an example configuration](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html)
=> nginx: add "/basic_status" job

modules/whoisquery/collect.go, modules/whoisquery/provider.go, modules/whoisquery/whoisquery_test.go
The issue is reported in https://community.netdata.cloud/t/support-more-tlds-with-go-d-whoisquery/1839/2
No need in validating domains.
=> whoisquery: remove domain validation

pkg/prometheus/prometheus.go
=> fix(prometheus): skip invalid metric type entries when parsing

modules/prometheus/charts.go, modules/prometheus/collect.go, modules/prometheus/collect_gauge_counter.go, modules/prometheus/collect_histogram.go, modules/prometheus/collect_summary.go, modules/prometheus/prometheus.go
Fixes: netdata/netdata#12572
After this PR a chart's context will be: `prometheus.{application}.{metric_name}`. If "application" is not in the configuration the job name is used.
I keep "prometheus" prefix because our current parser is prometheus parser.
=> feat(prometheus): add a config option to set application

config/go.d/nginx.conf
Two more `stub_status` locations are commonly used, `nginx_status` and `status`. This PR adds the relevant NGINX jobs.
Tested with Ubuntu 20.04 and NGINX 1.18.0. Also with the NGINX package provided by Bitnami.
=> feat(nginx): add common stub_status locations

modules/weblog/logline.go, modules/weblog/logline_test.go
This commit changes the way how the upstream_response_time field is
parsed in nginx access logs. The field can contain multiple time values
if the request got processed by multiple upstream servers, or if it
passed through an internal redirect between multiple server groups (i.e.
by using the X-Accel-Redirect header).
Previously, only the first encountered value was processed by weblog
plugin, and it only accounted for the ',' separator. If the field contained
the ':' separator, the value was not parsed correctly. With this commit
applied, both of these cases will be handled correctly. Additionaly, the
value reported will be the sum of times from all upstream servers that
handled the request, i.e. the total time the request spent upstream.
=> weblog: Correctly parse multiple values in nginx upstream_response_time

modules/postgres/README.md, modules/postgres/charts.go, modules/postgres/collect.go, modules/postgres/collect_checkpoints.go, modules/postgres/collect_connections.go, modules/postgres/collect_databases.go, modules/postgres/postgres.go, modules/postgres/postgres_test.go, modules/postgres/queries.go, modules/postgres/testdata/v14.4/database_stats.txt
Part of netdata/netdata#13387
This PR implements collecting connections utilization per database. This is handy when `CONNECTION LIMIT` is set on database creation.
=> feat(postgres): collect connections % per database

modules/snmp/charts.go
Fixes: netdata/netdata#13315
I think the correct fix is to set the dimension algorithm (if not explicitly set) based on the metric type (Counter - incremental, Gauge - absolute), but this fix will do for now.
=> fix(snmp): inherit dim algorithm if not set

README.md, config/go.d.conf, config/go.d/docker.conf, go.mod, go.sum, modules/docker/README.md, modules/docker/charts.go, modules/docker/collect.go, modules/docker/docker.go, modules/docker/docker_test.go, modules/init.go
Replacement for [python.d/dockerd](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/dockerd) and probably [go.d/docker_engine](https://github.com/netdata/go.d.plugin/tree/master/modules/docker_engine).
The collector is omega basic (the goal is to replace python.d/dockerd), and can be improved a lot.
=> feat: add Docker Engine collector

modules/postgres/charts.go
Came here to fix a typo (withing -> within) but decided it was better to remove "withing limits" entirely.
=> Fix a typo

modules/docker/README.md, modules/docker/charts.go, modules/docker/collect.go, modules/docker/docker.go, modules/docker/docker_test.go
[Data usage call](https://docs.docker.com/engine/api/v1.41/#tag/System/operation/SystemDataUsage) (`docker system df`) consumes a lot of CPU. Unfortunately, that was the only way to collect volume data usage.
Before/After
=> docker: remove data usage call

config/go.d/phpfpm.conf, modules/phpfpm/README.md, modules/phpfpm/client.go, modules/phpfpm/init.go, modules/phpfpm/phpfpm.go
With this change, you can monitor non-socket PHP-FPM instances (PHP-FPM does not allow you to listen on a socket and a port at the same time) without a webserver.
=> [phpfpm] Added ability to directly connect to a TCP address:port and modify status path

modules/k8s_kubelet/kubelet.go, modules/k8s_kubeproxy/kubeproxy.go, modules/k8s_state/charts.go
Fixes: netdata/netdata#13663
Waiting for an [answer](https://github.com/netdata/netdata/issues/13663#issuecomment-1246630763) before merging.
=> make k8s_* collectors chart priority higher than cgroups

config/go.d.conf, modules/init.go, modules/nvidia_smi/README.md, modules/nvidia_smi/charts.go, modules/nvidia_smi/collect.go, modules/nvidia_smi/exec.go, modules/nvidia_smi/init.go, modules/nvidia_smi/nvidia_smi.go, modules/nvidia_smi/nvidia_smi_test.go, modules/nvidia_smi/testdata/rtx-2080-win.xml, modules/nvidia_smi/testdata/rtx-3060.xml, modules/nvidia_smi/testdata/tesla-p100.xml
- uses the `nvidia-smi` tool to collect metrics.
- initial version will use XML format only and be disabled by default (needed for deprecating the python version first).
- csv support (much faster, but [fewer metrics](https://github.com/netdata/netdata/issues/10362#issuecomment-1022174067)) will be added later.
=> feat: add nvidia_smi collector

modules/redis/README.md, modules/redis/charts.go, modules/redis/collect.go, modules/redis/init.go, modules/redis/redis.go, modules/redis/redis_test.go
Part of netdata/netdata#13687
- send 5 [PING](https://redis.io/commands/ping/) commands.
- measure the elapsed time.
- calc min, max, and average.
=> feat(redis): add ping latency chart

modules/wmi/README.md
The provided link mentioned `msi`, but we mentioned `exe`, making it confusing.
=> Clarify windows_exporter installation instructions

modules/cassandra/README.md, modules/cassandra/cassandra_test.go, modules/cassandra/charts.go, modules/cassandra/collect.go, modules/cassandra/metrics.go, modules/cassandra/testdata/jmx_exporter.yaml
querying table metrics (seems) puts a lot of pressure on Cassandra, not needed because we don't really use them.
=> fix(cassandra): don't collect and blacklist table metric for now

modules/wmi/collect_process.go
During the development of IIS module I observed that we inverted the caller to remove charts.
=> Change call for proper function

modules/whoisquery/provider.go
Reported in https://community.netdata.cloud/t/whois-query-monitor-cannot-parse-expiration-time/3485
=> fix(whoisquery): handle ExpirationDate with space

modules/postgres/queries.go
In the case of specific characters in schema or table names, the request failed with: `ERROR:  relation "schemaname.relname" does not exist`
=> fix(postgres):  protect schema/table names with quote_ident

modules/postgres/queries.go
if the table is not in public or search_path, it can not find the pg_relation_size for the indexrelname
=> fix(postgres): add missing schemaname to indexrelname when using pg_relation_size

modules/nvidia_smi/README.md, modules/nvidia_smi/charts.go, modules/nvidia_smi/collect_xml.go, modules/nvidia_smi/nvidia_smi_test.go
=> feat(nvidia-smi): collect Voltage (XML only)

agent/job/discovery/file/parse.go, agent/setup.go
https://github.com/netdata/go.d.plugin/pull/1075 follow-up PR.
We have no logic that handles module renaming. It is the first time we do it, so not sure we need it all. This is just a quick and temporary fix. We need to announce this change in the next Netdata release notes and then remove it.
=> prefer user wmi.conf over windows.conf

README.md, pkg/README.md, pkg/iprange/README.md, pkg/matcher/README.md, pkg/prometheus/selector/README.md, pkg/stm/README.md, pkg/tlscfg/README.md, pkg/web/README.md
Related to netdata/learn#1349 
This is a WIP PR intended to fix broken links in markdown files, if there are any issues, where the missing link's info didn't get moved, but deleted, I will add checkbox items to decide what we should do about it.
- The [Contributing](https://github.com/netdata/go.d.plugin/blob/master/README.md?plain=1#:~:text=%23%23%20Contributing,done%20with%20testing.) section in the `README.md` has some old Learn links, and I removed a link that referred to a missing document.
- [The pulsar README](https://github.com/netdata/go.d.plugin/blob/master/modules/pulsar/README.md?plain=1#:~:text=To%20check%20matcher,matcher/README.md).) has a link to [`/pkg/matcher/README.md`](https://github.com/netdata/go.d.plugin/blob/master/pkg/matcher/README.md?plain=1) which we don't …
=> Fix broken links in .md files

modules/rabbitmq/metrics.go
=> fix(rabbitmq): use int64 for metrics

modules/windows/README.md
Closes https://github.com/netdata/learn/issues/1486
- Don't use [] tags for "Optional" noting, as this is a reserved symbol for markdown links.
- Changed links that pointed to `learn.netdata.cloud` to point to the respective GitHub page
=> Replace links to learn pages with github links

modules/docker/collect.go, modules/docker/docker.go, modules/docker/docker_test.go
Fix the problem [reported on Community Forum](https://community.netdata.cloud/t/docker-stats-broken-on-v1-38-0-153-nightly-on-v1-37-0-91-g6954b6f88-it-works/3900/12?u=ilyam8)
=> docker: add api version negotiation

config/go.d/elasticsearch.conf
Related [discussion in Community Forum](https://community.netdata.cloud/t/opensearch-elasticsearch-alternative-does-not-appear-automatically/3995).
=> add opensearch job config

modules/filecheck/collect.go, modules/filecheck/collect_dirs.go, modules/filecheck/collect_files.go
=> filecheck: replace space with underscore in dim

config/go.d/ping.conf, modules/ping/init.go, modules/ping/ping.go, modules/ping/prober.go
Implements https://github.com/netdata/netdata/discussions/15056
This PR adds the `interface` configuration option. If set, ping will attempt to use the interface's IP address as the source of ICMP packets.
> **Note**: only IPv4 address support added. I don't have a VM with v6 configured to test the change.
=> feat(ping): add 'interface' option

modules/apache/metadata.yaml
Don't know how we didn't spot this, but that line is wrong
=> fix apache/metadata.yaml

modules/activemq/metadata.yaml, modules/apache/metadata.yaml, modules/cassandra/metadata.yaml, modules/chrony/metadata.yaml
activemq, apache, cassandra and chrony were made to be valid against the related schema.
=> Make four module yamls fit schema

modules/activemq/metadata.yaml, modules/apache/metadata.yaml, modules/elasticsearch/metadata.yaml, modules/envoy/metadata.yaml, modules/geth/metadata.yaml, modules/k8s_kubelet/metadata.yaml, modules/k8s_kubeproxy/metadata.yaml, modules/lighttpd/metadata.yaml, modules/mysql/metadata.yaml, modules/nginx/metadata.yaml, modules/nginxvts/metadata.yaml, modules/postgres/metadata.yaml, modules/pulsar/metadata.yaml, modules/redis/metadata.yaml, modules/springboot2/metadata.yaml, modules/zookeeper/metadata.yaml
This is the second part of https://github.com/netdata/go.d.plugin/pull/1317. It needs to wait to be merged until _after_ https://github.com/netdata/netdata/pull/15863 gets merged in the agent repo.
=> Update related resources sections to use ids.

modules/openvpn_status_log/collect.go
`UNDEF` clients should not be counted, [as it means](https://forums.openvpn.net/viewtopic.php?p=89781#p89781) the connection is not established yet. If you don't use `tls-auth` in the openvpn server config, [random UDP packets or DoS](https://sourceforge.net/p/openvpn/mailman/openvpn-users/thread/alpine.LRH.1.10.0810221455570.5642%40rhlx09.hs-esslingen.de/#msg20611785) could also create a lot of `UNDEF` users in the status files.
The old [python-based openvpn plugin handled this](https://github.com/netdata/netdata/pull/3734) as well and the current `openvpn` module seems to have [special handling](https://github.com/netdata/go.d.plugin/blob/5fa3ff0de80f2a9055c1d1983e0cf1aada48dfbf/modules/openvpn/collect.go#L55) of `UNDEF` too.
=> openvpn_status_log: Do not count "UNDEF" users

modules/mysql/collect.go
Sometimes under heavy load on a read replica `SHOW ALL SLAVES STATUS` freeze and does not complete in time. This breaks the statistics collection. If you don't mind, it would be great if timeout errors were not considered so critical
=> Do not stop collecting mysql statistics because of timeout

go.mod, go.sum
cross-compilation is not possible on freebsd after they added FreeBSD support (needs freebsd vm + cgo).
=> downgrade wgctrl

cmd/godplugin/main.go, logger/severity.go
This env var will be added in netdata/netdata#14727
=> respect env NETDATA_LOG_SEVERITY_LEVEL

modules/prometheus/metadata.yaml
related discussion: https://netdata-cloud.slack.com/archives/CLVTYCQBD/p1696254773237659
Essentially we don't want to have two integrations named the same, and going to the same category, as it messes up Learn, and also confuses the user imo.
=> Update modules/prometheus/metadata.yaml to not have conflicting names with native collectors

agent/agent.go
Needed because netdata/netdata#16079 is not fixed yet
=> enable Dyncfg only in debug mode

modules/mysql/collect_global_vars.go, modules/mysql/collect_process_list.go, modules/mysql/mysql.go, modules/mysql/mysql_test.go, modules/mysql/testdata/mariadb/v10.8.4-galera-cluster/global_variables.txt, modules/mysql/testdata/mariadb/v10.8.4/global_variables.txt, modules/mysql/testdata/mysql/v8.0.30/global_variables.txt, modules/mysql/testdata/percona/v8.0.29/global_variables.txt
INFORMATION_SCHEMA.PROCESSLIST is deprecated and subject to removal in a future MySQL release. As such, the implementation of SHOW PROCESSLIST which uses that table is also deprecated.
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-35.html#mysqld-8-0-35-deprecation-removal
The new Performace Schema implementation is available since 8.0.22. https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-22.html#mysqld-8-0-22-performance-schema
=> mysql: Use Performance Schema processlist implementation if available

go.mod, go.sum
=> Set required golang to 1.21

.gitignore, Makefile, hack/go-build.sh
Would it be possible to release vendor archives for new versions? This is how it can be done. I tried to integrate it to a current workflow.
=> Vendor archives

modules/postgres/do_query_databases.go, modules/postgres/postgres_test.go, modules/postgres/queries.go
Fixes: netdata/netdata#16506
[pg_database_size()](https://pgpedia.info/p/pg_database_size.html)
> can be executed by any user with the CONNECT privilege for the database, **or (from [PostgreSQL 10](https://pgpedia.info/postgresql-versions/postgresql-10.html)) any user who is member of the pg_read_all_stats role**.
This PR implements the **or** part.
=> fix(postgres): add "user a member of pg_read_all_stats" check when querying db size for v10+

agent/confgroup/group.go, agent/hostinfo/hostinfo.go, agent/hostinfo/hostinfo_common.go, agent/hostinfo/hostinfo_linux.go, agent/setup.go
Fixes: netdata/netdata#15930
Known issue: go.d/logind high CPU usage on Alma Linux 8 (systemd 239).
=> disable logind on systemd 239 by default
